# Generated by Django 3.2.5 on 2021-07-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entidad_Federativa', models.CharField(max_length=35)),
                ('Municipio', models.CharField(max_length=35)),
                ('Nombre', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
